---
image: docker.io/library/golang:1.18

stages:
- build
- test

go-build:
  stage: build
  script: go build ./...

go-fmt:
  stage: test
  script: go fmt ./...

go-test:
  stage: test
  script: go test -race ./...
